// <auto-generated />
using C_Learn.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace C_Learn.Migrations
{
    [DbContext(typeof(APIContext))]
    [Migration("20251022070716_book data seeded")]
    partial class bookdataseeded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("C_Learn.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scott Fitzgerald",
                            Title = "The Great Gatsby",
                            YearPublished = 1925
                        },
                        new
                        {
                            Id = 2,
                            Author = "Harper Lee",
                            Title = "To Kill a Mocckingbird",
                            YearPublished = 1960
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            Title = "1984",
                            YearPublished = 1949
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jane Austen",
                            Title = "Pride and Prejudice",
                            YearPublished = 1813
                        },
                        new
                        {
                            Id = 5,
                            Author = "Herman Melville",
                            Title = "Moby-Dick",
                            YearPublished = 1851
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
